#!/bin/sh
set -e

case "$1" in
    install|upgrade)
    echo "# This file is empty, feel free to
# add here your custom APT repositories


#############
#  WARNING  #
#############

# ADDING EXTERNAL REPOSITORIES MAY HARM YOUR SYSTEM,
# MAY INTRODUCE MALWARE, CAUSE INSTABILITY OR
# CAUSE PERMANENT DATA LOSS
#    DO IT WISELY

# The default CtxOS repositories
# are NOT here. If you want to
# edit them, take a look into
#    /etc/apt/sources.list.d/ctxos.list

# if the default servers are too slow
# open /etc/apt/sources.list.d/ctxos.list
# and follow the instructions to choose faster servers
" > /etc/apt/sources.list
        ;;
esac
