#!/usr/bin/env bash
# generate-release-notes.sh - Create professional release notes for CtxOS
set -e

VERSION=$(cat VERSION)
NOTES_FILE="RELEASE_NOTES.md"
DATE=$(date +"%Y-%m-%d")

log() { echo -e "\033[0;32m[NOTES]\033[0m $1"; }

log "Generating release notes for v$VERSION..."

cat <<EOF > "$NOTES_FILE"
# 🚀 CtxOS v$VERSION
**Release Date:** $DATE

## 🌟 Overview
Version $VERSION of CtxOS introduces significant enhancements to system resilience, multi-platform support, and OEM customization.

## 📦 Changes in this version
\$(if [ -f software-center/debian/changelog ]; then
    head -n 10 software-center/debian/changelog | grep -E "^\s+\*" | sed 's/^\s+/- /'
fi)

## 🛠️ Infrastructure Updates
- **Global Localization:** Added support for multi-language UI (EN/ES).
- **Snapshot Protection:** Automatic restore points before system-wide changes.
- **Hardware Intelligence:** Smart driver & stack suggestions for NVIDIA/Intel/AMD.
- **Multi-Platform:** Official support for Docker, QEMU VMs, and WSL2.

## 🏗️ Artifacts
- **Software Center .deb**: Core management interface.
- **Docker Image**: \`debian-base-kit:$VERSION\`
- **Live ISO**: Available for hardware validation.

## 🛰️ Fleet Status
Node health can be monitored via the built-in Fleet Manager.

---
*Generated by the CtxOS Pipeline Master.*
EOF

log "Release notes saved to $NOTES_FILE"

# Generate website/releases.json
cat <<EOF > "website/releases.json"
[
  {
    "version": "$VERSION",
    "date": "$DATE",
    "highlights": [
      "Global Localization Support (EN/ES)",
      "Automated Snapshot Protection",
      "Multi-Platform (Docker, VM, WSL) Readiness",
      "Intelligent Hardware Detection"
    ]
  }
]
EOF
log "Website releases.json updated."
